import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";


export default function Home() {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <main className="flex flex-col items-center pt-4">Loading...</main>
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center">
        <h1 className="text-3xl pt-4">Vahiny</h1>
        <p>made with <code>create-t3-app</code></p>
        <div className="pt-10">
          <div>
            {session ? (
              <>
                <p className="mb-4 text-center">Hi {session.user?.name}</p>
                <button
                  type="button"
                  className="bg-red-500 p-2 rounded-lg place-content-center"
                  onClick={() => {
                    signOut().catch(console.log);
                  }}>Logout</button>
              </>) : (
              <>
                <p className="mb-4 text-center">You are not logged in</p>
                <button
                  className="bg-purple-600 p-2 rounded-lg"
                  onClick={() => {
                    signIn("discord").catch(console.log);
                  }}>Log in with Discord</button>
              </>
            )}
          </div>
        </div>
      </main>
    </>
  );
}


